name = "Apophis"
uuid = "cf72b054-1e85-4718-a3f4-02cfdc10a054"
authors = ["moataz-sabry <moataz.sabry@outlook.de>", "Ahmed Hassan <a.hassan@itv.rwth-aachen.de>"]
version = "1.3.4"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
PyCall = "1.95.1"
SplitApplyCombine = "1.2.2"
Unitful = "1.12.3"
YAML = "0.4.8"
Zygote = "0.6.55"
julia = "1.8.5"

[extras]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PyCall", "Test"]
